CREATE TABLE IF NOT EXISTS Tag (
TagId INTEGER PRIMARY KEY AUTOINCREMENT, 
Name NVARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Owner (
OwnerId INTEGER PRIMARY KEY AUTOINCREMENT,
Name NVARCHAR(200) NOT NULL,
ContactDetails NVARCHAR(500)
);

CREATE TABLE IF NOT EXISTS GamingServer(
GamingServerId INTEGER PRIMARY KEY AUTOINCREMENT,
Name NVARCHAR(200) NOT NULL,
Description NVARCHAR(500) NOT NULL,
GamingServerLink NVARCHAR(300) NOT NULL,
Port INTEGER NOT NULL,
OwnerId INTEGER,
FOREIGN KEY (OwnerId) REFERENCES Owner(OwnerId)
);

CREATE TABLE IF NOT EXISTS GamingServerTag(
GamingServerId INTEGER NOT NULL,
TagId INTEGER NOT NULL,
FOREIGN KEY (GamingServerId) REFERENCES Server(GamingServerId),
FOREIGN KEY (TagId) REFERENCES Tag(TagId)
);

CREATE TABLE IF NOT EXISTS GamingServerImage(
GamingServerImageId INTEGER PRIMARY KEY AUTOINCREMENT,
Content BLOB NOT NULL,
ServerId INTEGER NOT NULL,
FOREIGN KEY (GamingServerId) REFERENCES Server(GamingServerId)
);

CREATE TABLE IF NOT EXISTS GamingServerSubscription(
GamingServerSubscriptionId INTEGER PRIMARY KEY AUTOINCREMENT,
AvailableFrom datetime NOT NULL,
AvailableUntil datetime NOT NULL,
GamingServerId INTEGER NOT NULL,
FOREIGN KEY (GamingServerId) REFERENCES Server(GamingServerId)
);

